# Define the workflow name
name: Built And Test Workflow

# Define events on which this workflow will be triggered.
on:
  push: # Push event
    branches:
      - main # on main branch

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest # Selecting Runner

    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v5

        # 2. Setup build environment
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

        # 3. Install project dependencies
      - name: Install Project Dependencies
        run: npm ci

      - name: Run Unit Testing
        run: npm run test

        # Creating production build
      - name: Build Project
        run: npm run build

        # Display github context
      - name: Display Context
        run: |
          echo "-----Github Context-----"
          echo '${{toJSON(github)}}'

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Vercel Build and Deploy
        run: |
          vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}}
          vercel build --token=${{secrets.VERCEL_TOKEN}}
          vercel deploy --prebuilt --token=${{secrets.VERCEL_TOKEN}}
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
          VERCEL_ORG_ID: ${{secrets.VERCEL_USER_ID}}
          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
