# Define the workflow name
name: Built And Test Workflow

# Define events on which this workflow will be triggered.
on:
  push: # Push event
    branches:
      - main # on main branch

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest # Selecting Runner

    steps:
      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v5

        # 2. Setup build environment
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20.x

        # 3. Install project dependencies
      - name: Install Project Dependencies
        run: npm ci

      - name: Run Unit Testing
        run: npm run test

        # Creating production build
      - name: Build Project
        run: npm run build

        # Display github context
      - name: Display Context
        run: |
          echo "-----Github Context-----"
          echo '${{toJSON(github)}}'
